### ISSUE TITLE
Comment moved to different line in comma-separated arguments

### ISSUE THREAD

**Issue by noahbetzen-wk** [jhipster/prettier-java#382]
**Prettier-Java 0.7.1**

```yaml
    options:
      printWidth: 120
      tabWidth: 4
      useTabs: false
```

**Diff**

(Redacted because of proprietary code, but hopefully the issue is understandable)

<img width="478" alt="Screen Shot 2020-03-31 at 11 13 07 AM" src="https://user-images.githubusercontent.com/31736963/78050830-6fdcd280-7342-11ea-8e94-a5d54a3a9ce6.png">

I'll attempt to recreate a minimum viable example ASAP.

**Expected behavior:**

Don't move the comment.
