### ISSUE TITLE
Cannot set tabWidth

### ISSUE THREAD

**Issue by ricardobeat** [jhipster/prettier-java#430]
Android code uses four spaces. I am unable to set `tabWidth` via `.prettierrc` when using prettier-java, either at the root level or inside the source folder. 

Is it possible to override [the defaults](https://github.com/jhipster/prettier-java/blob/master/.prettierrc.yaml)?

**Comment by pascalgrimaud** [comment]
@ricardobeat : try this https://github.com/jhipster/generator-jhipster/blob/main/.prettierrc#L14-L18

```
# java rules:
overrides:
  - files: "*.java"
    options:
      tabWidth: 4
```

**Comment by ricardobeat** [comment]
> I am unable to set tabWidth via .prettierrc
> either at the root level or inside the source folder

does not work for me.

**Comment by pascalgrimaud** [comment]
My `.prettierrc` file :

```
➜ cat .prettierrc 
# Prettier configuration

printWidth: 140
singleQuote: true
tabWidth: 2
useTabs: false

# js and ts rules:
arrowParens: avoid

# jsx and tsx rules:
jsxBracketSameLine: false

# java rules:
overrides:
  - files: "*.java"
    options:
      tabWidth: 2
```

an extract of my package.json file :

```json
  "devDependencies": {
    "husky": "4.2.5",
    "lint-staged": "8.2.1",
    "prettier": "2.0.5",
    "prettier-plugin-java": "0.8.2"
  },
  "engines": {
    "node": ">=12.0.0"
  },
  "scripts": {
    "prettier:format": "prettier --write \"{,src/**/,.github/**}*.{md,json,yml,java}\""
  }
```

Then, everything is formatted with 2 spaces, instead of 4.
So unless you can push a project as example, we won't be able to reproduce your issue as it works well for my personal project, and it works well for generated JHipster project
