### ISSUE TITLE
How to enable in vscode

### ISSUE THREAD

**Issue by stephan-klein** [jhipster/prettier-java#706]
I read all the guides still im puzzled how to enable the plugin in vscode.

I execute

npm install --save-dev --save-exact prettier prettier-plugin-java

I have the prettier extension installed.

and now ? how can i enable the formatting ? Still my other java formatter is executed.

when i put
```
"[java]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
```
in settings.json 

i get

![image](https://github.com/user-attachments/assets/333cb01f-2843-48fd-945b-500bc9d4b7c2)

How to link the plugin to formatting action ?

**Comment by clementdessoude** [comment]
Hello @stephan-klein !

Do you have a [Prettier configuration file](https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option) ? 
If not, can you try creating one like this one (you can convert this one from yaml to any other format) and see if if fixes your issue ?

```yaml
# Prettier configuration
plugins:
  - prettier-plugin-java
overrides:
  - files:
      - "*.java"
    options:
      printWidth: 100
      tabWidth: 4
      useTabs: false
      trailingComma: "none"
```
